#!/usr/bin/env bash

LAYOUT=$(hyprctl devices -j | jq '.keyboards.[] | select(.name == "at-translated-set-2-keyboard") | .active_keymap')
SHORT=""
case $LAYOUT in
  '"Swedish"')
    SHORT="SV";;
  *)
    SHORT="EN";;
esac

# When return-type is set to json, waybar expects a single line:
printf '{"text":"%s","tooltip":%s}' "$SHORT" "$LAYOUT"
