#!/usr/bin/env sh

# Startup

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Config

yabai -m config	\
	layout bsp \
	window_gap 12 \
	top_padding 12 \
	bottom_padding 12 \
	left_padding 12 \
	right_padding 12

echo "yabai config loaded."
